// Auto-generated by tools/generate-protocol.mjs from protocol/bridge-v1.schema.json - DO NOT EDIT MANUALLY
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace GameBuddy.Stardew.Core.Protocol;

public sealed record ExecutionRequestDto(
    [property: JsonPropertyName("requestId")] string RequestId,
    [property: JsonPropertyName("idempotencyKey")] string IdempotencyKey,
    [property: JsonPropertyName("action")] string Action,
    [property: JsonPropertyName("expectedRevision")] long ExpectedRevision,
    [property: JsonPropertyName("deadlineMs")] long DeadlineMs,
    [property: JsonPropertyName("args")] IReadOnlyDictionary<string, JsonElement> Args
);

public sealed record ExecutionReceiptDto(
    [property: JsonPropertyName("executionId")] string ExecutionId,
    [property: JsonPropertyName("requestId")] string RequestId,
    [property: JsonPropertyName("state")] string State,
    [property: JsonPropertyName("reasonCode")] string ReasonCode,
    [property: JsonPropertyName("revision")] long Revision,
    [property: JsonPropertyName("evidence")] IReadOnlyDictionary<string, JsonElement>? Evidence
);
