[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if ($env:OS -ne 'Windows_NT') { throw 'windows_named_mutex_required' }

Add-Type -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
namespace GameBuddy.NamedMutexBroker {
 public sealed class Store : IDisposable {
  sealed class Held { public readonly string TargetId; public readonly Mutex Mutex; public readonly AutoResetEvent Release=new AutoResetEvent(false); public readonly ManualResetEvent Released=new ManualResetEvent(false); public Held(string targetId,Mutex mutex) { TargetId=targetId; Mutex=mutex; } }
  sealed class Pending { public readonly string Name; public readonly CancellationTokenSource Cancel=new CancellationTokenSource(); public readonly ManualResetEvent Completed=new ManualResetEvent(false); public Pending(string name) { Name=name; } }
  sealed class TerminalRecord { public readonly string Name; public readonly string State; public TerminalRecord(string name,string state) { Name=name; State=state; } }
  readonly Dictionary<string,Held> held=new Dictionary<string,Held>(); readonly Dictionary<string,Pending> pending=new Dictionary<string,Pending>(); readonly Dictionary<string,TerminalRecord> terminals=new Dictionary<string,TerminalRecord>(); readonly Queue<string> terminalOrder=new Queue<string>(); readonly object gate=new object(); static readonly object output=new object(); const int WaitMs=1000; const int CancelWaitMs=5000; const int MaxTerminalRecords=128;
  static void Reply(string id,bool ok,string code,string targetId=null,string name=null,string terminal=null) { lock(output) { var suffix=targetId==null ? "" : ",\"targetId\":\""+targetId+"\",\"name\":\""+name+"\",\"terminal\":\""+terminal+"\""; Console.Out.WriteLine("{\"id\":\""+id+"\",\"ok\":"+(ok?"true":"false")+",\"code\":\""+code+"\""+suffix+"}"); Console.Out.Flush(); } }
  void Terminal(string id,string name,string state) { lock(gate) { terminals[id]=new TerminalRecord(name,state); terminalOrder.Enqueue(id); while(terminalOrder.Count>MaxTerminalRecords) { var expired=terminalOrder.Dequeue(); terminals.Remove(expired); } Pending p; if(pending.TryGetValue(id,out p)) { pending.Remove(id); p.Completed.Set(); p.Cancel.Dispose(); } } }
  bool TerminalHeld(string id,string name,Held h,Pending p) { lock(gate) { if(p.Cancel.IsCancellationRequested) { Held current; if(held.TryGetValue(name,out current) && Object.ReferenceEquals(current,h)) held.Remove(name); return false; } pending.Remove(id); p.Completed.Set(); p.Cancel.Dispose(); return true; } }
  void BeforeHeldTerminalForTest() { var marker=Environment.GetEnvironmentVariable("GAMEBUDDY_TEST_ONLY_NAMED_MUTEX_BROKER_BEFORE_HELD_TERMINAL_MARKER"); if(!String.IsNullOrEmpty(marker)) System.IO.File.WriteAllText(marker,"before_held_terminal"); if(Environment.GetEnvironmentVariable("GAMEBUDDY_TEST_ONLY_NAMED_MUTEX_BROKER_DELAY_BEFORE_HELD_TERMINAL_MS")=="1") Thread.Sleep(1000); }
  void CancelledAfterAcquire(string id,string name,Mutex mutex) { try { mutex.ReleaseMutex(); } catch {} try { mutex.Dispose(); } catch {} Terminal(id,name,"cancelled"); Reply(id,false,"cancelled"); }
  public void BeginAcquire(string id,string name,int timeoutMs) { var p=new Pending(name); lock(gate) pending.Add(id,p); Task.Run(() => { Mutex mutex=null; Held h=null; bool added=false; try { mutex=new Mutex(false,name); var started=Environment.TickCount; bool acquired=false; if(Environment.GetEnvironmentVariable("GAMEBUDDY_TEST_ONLY_NAMED_MUTEX_BROKER_FORCE_ABANDONED")=="1") throw new AbandonedMutexException(); while(!p.Cancel.IsCancellationRequested && !(acquired=mutex.WaitOne(50))) if(unchecked(Environment.TickCount-started)>=timeoutMs) break; if(p.Cancel.IsCancellationRequested) { Reply(id,false,"cancelled"); Terminal(id,name,"cancelled"); return; } if(!acquired) { Reply(id,true,"timeout"); Terminal(id,name,"timeout"); return; } lock(gate) { if(p.Cancel.IsCancellationRequested || held.ContainsKey(name)) { CancelledAfterAcquire(id,name,mutex); mutex=null; return; } h=new Held(id,mutex); held.Add(name,h); added=true; } BeforeHeldTerminalForTest(); if(!TerminalHeld(id,name,h,p)) { added=false; CancelledAfterAcquire(id,name,mutex); mutex=null; return; } Reply(id,true,"acquired"); mutex=null; HoldUntilReleased(name,h); } catch(AbandonedMutexException) { lock(gate) { if(p.Cancel.IsCancellationRequested || held.ContainsKey(name)) { CancelledAfterAcquire(id,name,mutex); mutex=null; return; } h=new Held(id,mutex); held.Add(name,h); added=true; } BeforeHeldTerminalForTest(); if(!TerminalHeld(id,name,h,p)) { added=false; CancelledAfterAcquire(id,name,mutex); mutex=null; return; } Reply(id,true,"abandoned"); mutex=null; HoldUntilReleased(name,h); } catch { if(added && h!=null) Rollback(name,h); Reply(id,false,"acquire_failed"); Terminal(id,name,"failed"); } finally { if(mutex!=null) { try { mutex.Dispose(); } catch {} } } }); }
  void HoldUntilReleased(string name,Held h) { try { h.Release.WaitOne(); try { h.Mutex.ReleaseMutex(); } finally { h.Mutex.Dispose(); h.Released.Set(); } } catch { Rollback(name,h); } }
  void Rollback(string name,Held h) { lock(gate) { Held current; if(held.TryGetValue(name,out current) && Object.ReferenceEquals(current,h)) held.Remove(name); } try { h.Mutex.ReleaseMutex(); } catch {} try { h.Mutex.Dispose(); } catch {} try { h.Released.Set(); } catch {} }
  public string Cancel(string id,string name) { Pending p=null; lock(gate) { if(pending.TryGetValue(id,out p)) { if(p.Name!=name) return "failed"; p.Cancel.Cancel(); } else { Held h; if(held.TryGetValue(name,out h) && h.TargetId==id) return "held"; TerminalRecord terminal; if(!terminals.TryGetValue(id,out terminal) || terminal.Name!=name) return "failed"; terminals.Remove(id); return terminal.State; } } if(!p.Completed.WaitOne(CancelWaitMs)) return "failed"; lock(gate) { Held h; if(held.TryGetValue(name,out h) && h.TargetId==id) return "held"; TerminalRecord terminal; if(!terminals.TryGetValue(id,out terminal) || terminal.Name!=name) return "failed"; terminals.Remove(id); return terminal.State; } }
  public bool Release(string name) { Held h; lock(gate) { if(!held.TryGetValue(name,out h)) return false; held.Remove(name); } h.Release.Set(); if(!h.Released.WaitOne(WaitMs)) { Rollback(name,h); return false; } h.Release.Dispose(); h.Released.Dispose(); return true; }
  public void Dispose() { string[] names; lock(gate) names=new List<string>(held.Keys).ToArray(); foreach(var name in names) Release(name); }
 }
}
'@
$store=[GameBuddy.NamedMutexBroker.Store]::new()
function Write-Reply([string]$id,[bool]$ok,[string]$code,[string]$targetId=$null,[string]$name=$null,[string]$terminal=$null) { $reply=[ordered]@{id=$id;ok=$ok;code=$code}; if(-not [string]::IsNullOrEmpty($targetId)){$reply.targetId=$targetId;$reply.name=$name;$reply.terminal=$terminal}; [Console]::Out.WriteLine(($reply|ConvertTo-Json -Compress));[Console]::Out.Flush() }
function Valid-Name([object]$name) { return $name -is [string] -and $name.StartsWith('Local\GameBuddy.Host.') -and $name.Substring(21) -match '^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$' }
try { while (($line=[Console]::In.ReadLine()) -ne $null) { if($line.Length -gt 4096){Write-Reply '' $false 'protocol_line_too_long';continue}; try{$request=$line|ConvertFrom-Json -ErrorAction Stop}catch{Write-Reply '' $false 'invalid_protocol_json';continue}; $properties=@($request.PSObject.Properties);$names=@($properties|ForEach-Object{$_.Name}); if($null -eq $request -or $names -notcontains 'id' -or $names -notcontains 'op' -or $names -notcontains 'name' -or $names -notcontains 'timeoutMs'){Write-Reply '' $false 'invalid_protocol_shape';continue}; if($request.id -isnot [string] -or $request.id -notmatch '^[a-f0-9-]{36}$'){Write-Reply '' $false 'invalid_protocol_id';continue}; if(-not(Valid-Name $request.name)){Write-Reply $request.id $false 'invalid_mutex_name';continue}; if($request.op -eq 'acquire'){if($properties.Count -ne 4 -or $request.timeoutMs -isnot [int] -or $request.timeoutMs -lt 0 -or $request.timeoutMs -gt 30000){Write-Reply $request.id $false 'invalid_timeout';continue};$store.BeginAcquire($request.id,$request.name,$request.timeoutMs)} elseif($request.op -eq 'cancel'){if($properties.Count -ne 5 -or $request.timeoutMs -ne 0 -or $request.targetId -isnot [string]){Write-Reply $request.id $false 'invalid_cancel_request';continue};$terminal=$store.Cancel($request.targetId,$request.name);Write-Reply $request.id $true 'cancelled' $request.targetId $request.name $terminal} elseif($request.op -eq 'release'){if($properties.Count -ne 4 -or $request.timeoutMs -ne 0){Write-Reply $request.id $false 'invalid_release_request';continue};if($store.Release($request.name)){Write-Reply $request.id $true 'released'}else{Write-Reply $request.id $false 'not_held'}} else{Write-Reply $request.id $false 'invalid_protocol_operation'} } } finally { $store.Dispose() }
