// Auto-generated by tools/generate-protocol.mjs from protocol/bridge-v1.schema.json - DO NOT EDIT MANUALLY

function deepFreeze<T>(value: T): T {
  if (value === null || typeof value !== "object") return value;
  for (const key of Object.getOwnPropertyNames(value)) {
    const val = (value as Record<string, unknown>)[key];
    if (val !== null && typeof val === "object") {
      deepFreeze(val);
    }
  }
  return Object.freeze(value);
}

export const EXECUTION_STATE_DTOS = Object.freeze([
  "accepted",
  "running",
  "meaningful_progress",
  "blocked",
  "invalidated",
  "succeeded",
  "partially_succeeded",
  "failed",
  "cancelled",
  "expired",
  "rejected",
  "uncertain",
] as const);
export type ExecutionStateDto =
  | "accepted"
  | "running"
  | "meaningful_progress"
  | "blocked"
  | "invalidated"
  | "succeeded"
  | "partially_succeeded"
  | "failed"
  | "cancelled"
  | "expired"
  | "rejected"
  | "uncertain";

export const EXECUTION_ACTION_DTOS = Object.freeze([
  "move_to_tile",
  "equip_tool",
  "travel",
  "enter_exit",
  "till_soil",
  "pickup_forage",
  "pickup_item",
  "water_crop",
  "harvest_crop",
  "plant_seed",
  "fertilize_tile",
  "place_wood_fence",
  "place_crab_pot",
  "bait_crab_pot",
  "clear_debris",
  "machine_inspect",
  "machine_load",
  "machine_collect_output",
  "npc_relationship",
  "pet_animal",
  "collect_animal_product",
  "feed_animal",
  "use_item",
  "chop_tree_source",
  "break_rock_source",
  "clear_hoedirt",
  "dig_artifact_spot",
  "refill_watering_can",
] as const);
export type ExecutionActionDto =
  | "move_to_tile"
  | "equip_tool"
  | "travel"
  | "enter_exit"
  | "till_soil"
  | "pickup_forage"
  | "pickup_item"
  | "water_crop"
  | "harvest_crop"
  | "plant_seed"
  | "fertilize_tile"
  | "place_wood_fence"
  | "place_crab_pot"
  | "bait_crab_pot"
  | "clear_debris"
  | "machine_inspect"
  | "machine_load"
  | "machine_collect_output"
  | "npc_relationship"
  | "pet_animal"
  | "collect_animal_product"
  | "feed_animal"
  | "use_item"
  | "chop_tree_source"
  | "break_rock_source"
  | "clear_hoedirt"
  | "dig_artifact_spot"
  | "refill_watering_can";

export interface ExecutionRequestDto {
  readonly requestId: string;
  readonly idempotencyKey: string;
  readonly action: ExecutionActionDto;
  readonly expectedRevision: number;
  readonly deadlineMs: number;
  readonly args: Readonly<Record<string, unknown>>;
}

export interface ExecutionReceiptDto {
  readonly executionId: string;
  readonly requestId: string;
  readonly state: ExecutionStateDto;
  readonly reasonCode: string;
  readonly revision: number;
  readonly evidence: Readonly<Record<string, unknown>> | null;
}

export function serializeExecutionRequest(req: ExecutionRequestDto): string {
  return JSON.stringify(req);
}

export function deserializeExecutionRequest(json: string): ExecutionRequestDto {
  let obj: any;
  try {
    obj = JSON.parse(json);
  } catch {
    throw new Error("invalid_request_json");
  }
  if (!obj || typeof obj !== "object" || Array.isArray(obj)) throw new Error("invalid_request_json");
  if (!obj.requestId || typeof obj.requestId !== "string") throw new Error("missing_required_field:requestId");
  if (!obj.idempotencyKey || typeof obj.idempotencyKey !== "string")
    throw new Error("missing_required_field:idempotencyKey");
  if (!obj.action || typeof obj.action !== "string") throw new Error("missing_required_field:action");

  const validActions = new Set<string>(EXECUTION_ACTION_DTOS);
  if (!validActions.has(obj.action)) {
    throw new Error("invalid_action:" + obj.action);
  }

  if (typeof obj.expectedRevision !== "number" || !Number.isInteger(obj.expectedRevision) || obj.expectedRevision < 0) {
    throw new Error("invalid_expectedRevision");
  }
  if (typeof obj.deadlineMs !== "number" || !Number.isInteger(obj.deadlineMs) || obj.deadlineMs <= 0) {
    throw new Error("invalid_deadlineMs");
  }
  if (obj.args === undefined || obj.args === null || typeof obj.args !== "object" || Array.isArray(obj.args)) {
    throw new Error("invalid_args");
  }

  return deepFreeze({
    requestId: obj.requestId,
    idempotencyKey: obj.idempotencyKey,
    action: obj.action,
    expectedRevision: obj.expectedRevision,
    deadlineMs: obj.deadlineMs,
    args: { ...obj.args },
  });
}

export function serializeExecutionReceipt(rec: ExecutionReceiptDto): string {
  return JSON.stringify(rec);
}

export function deserializeExecutionReceipt(json: string): ExecutionReceiptDto {
  let obj: any;
  try {
    obj = JSON.parse(json);
  } catch {
    throw new Error("invalid_receipt_json");
  }
  if (!obj || typeof obj !== "object" || Array.isArray(obj)) throw new Error("invalid_receipt_json");
  if (!obj.executionId || typeof obj.executionId !== "string") throw new Error("missing_required_field:executionId");
  if (!obj.requestId || typeof obj.requestId !== "string") throw new Error("missing_required_field:requestId");
  if (!("evidence" in obj)) throw new Error("missing_required_field:evidence");

  const validStates = new Set<string>(EXECUTION_STATE_DTOS);
  if (!validStates.has(obj.state)) {
    throw new Error("invalid_state:" + obj.state);
  }
  if (typeof obj.reasonCode !== "string") throw new Error("missing_required_field:reasonCode");
  if (typeof obj.revision !== "number" || !Number.isInteger(obj.revision) || obj.revision < 0) {
    throw new Error("invalid_revision");
  }

  let evidence: Readonly<Record<string, unknown>> | null = null;
  if (obj.evidence !== null) {
    if (typeof obj.evidence !== "object" || Array.isArray(obj.evidence)) {
      throw new Error("invalid_evidence");
    }
    evidence = { ...obj.evidence };
  }

  return deepFreeze({
    executionId: obj.executionId,
    requestId: obj.requestId,
    state: obj.state,
    reasonCode: obj.reasonCode,
    revision: obj.revision,
    evidence,
  });
}
