/**
 * Public semantic-store API. Production connection construction is deliberately
 * not re-exported: authority admission belongs exclusively to provisioning.
 */
export {
  ContinuityCommandError,
  openContinuitySemanticStore,
  previousRuntimeOwnerAlive,
  previousRuntimeOwnerAmbiguous,
  previousRuntimeOwnerMismatch,
  previousRuntimeOwnerProvenDead,
  previousRuntimeOwnerUnavailable,
  withImmediateTransaction,
} from "./continuity-semantic-store.production-internal.js";
export type {
  AdoptLegacyPartitionInput,
  ArchiveLifecycleCommand,
  AuthenticatedContinuityPrincipal,
  AuthoritativeSnapshot,
  ChatCommandReadback,
  ChatSelectionCommand,
  CommandErrorCode,
  ContinuityLease,
  ContinuitySemanticStore,
  ContinuitySemanticStoreOptions,
  ContinuityThread,
  DurablePreviousRuntimeOwner,
  GameAbortReason,
  GameCommand,
  GameCommandKind,
  GameCommandReadback,
  GameEffectFailureReason,
  GameOperationAbortInput,
  GameOperationCommitInput,
  GameOperationFailureInput,
  GamePermit,
  GamePrepareOutcome,
  GameRecoveryFacts,
  GameRecoveryReason,
  GameRevisionVector,
  GameTerminalCommand,
  GameTerminalReceipt,
  PreviousRuntimeOwnerVerificationResult,
  PreviousRuntimeOwnerVerifier,
  RegisterExactChatCommand,
  SemanticChatCatalog,
  InitialChatSagaClaim,
  InitialChatSagaChatRegistration,
  InitialChatSagaContentVerification,
  InitialChatSagaSelection,
  InitialChatSagaReadback,
  InitialChatSagaStore,
} from "./continuity-semantic-store.production-internal.js";
