using System.Collections;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Runtime.Loader;
using System.Security.Cryptography;
using System.Text.Json;

const string ExpectedAsset = "Maps/Mine";
const string ExpectedMapDigest = "a8669be89fd338360bbe637df3c383f3dc5f0d50b1028ad7385aeb39f6e700ff";
const string ManifestName = "probe-loader-manifest.json";
const string LockedTargetHash = "7f1e5b8e58d2758b78570ba771bbeb03d33522f62188bf6c32edf0cf626deaee";

if (args.Length == 2 && args[0] == "--discover") return Discover(Path.GetFullPath(args[1]));
if (args.Length != 1) { Console.Error.WriteLine("usage: PositionForMineEntryContentProbe --discover <game-root> | <private-snapshot-root>"); return 2; }
var root = Path.GetFullPath(args[0]);
if (!IsRegularDirectory(root)) { Console.Error.WriteLine("invalid_snapshot_root"); return 2; }
try
{
    var manifestPath = VerifiedRegularChild(root, ManifestName) ?? throw new InvalidOperationException("loader_manifest_missing");
    var manifest = JsonSerializer.Deserialize<LoaderManifest>(File.ReadAllText(manifestPath), new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? throw new InvalidOperationException("loader_manifest_invalid");
    ValidateManifest(manifest);
    var before = Snapshot(root, manifest.DeclaredSnapshotClosure);
    var alc = new LockedGameLoadContext(root, manifest);
    try
    {
        var monoGame = manifest.DeclaredSnapshotClosure.Single(x => x.RelativeFileName == "MonoGame.Framework.dll");
        var game = manifest.DeclaredSnapshotClosure.Single(x => x.RelativeFileName == "Stardew Valley.dll");
        var xTile = manifest.DeclaredSnapshotClosure.Single(x => x.RelativeFileName == "xTile.dll");
        AppDomain.CurrentDomain.SetData("APP_CONTEXT_BASE_DIRECTORY", root);
        var monoGameAssembly = alc.LoadVerified(monoGame);
        var titleContainer = monoGameAssembly.GetType("Microsoft.Xna.Framework.TitleContainer", true)!;
        var titleRoot = titleContainer.GetProperty("Location", BindingFlags.Static | BindingFlags.NonPublic) ?? throw new InvalidOperationException("title_container_root_property_missing");
        if (titleRoot.PropertyType != typeof(string) || !titleRoot.CanWrite || !titleRoot.CanRead) throw new InvalidOperationException("title_container_root_policy_failed");
        titleRoot.SetValue(null, root);
        if (!string.Equals((string?)titleRoot.GetValue(null), root, StringComparison.Ordinal)) throw new InvalidOperationException("title_container_root_readback_failed");
        var gameAssembly = alc.LoadVerified(game);
        var managerType = gameAssembly.GetType("StardewValley.LocalizedContentManager", true)!;
        var constructor = managerType.GetConstructors(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic).SingleOrDefault(c => c.GetParameters() is var p && p.Length == 2 && p[1].ParameterType == typeof(string)) ?? throw new InvalidOperationException("localized_content_manager_constructor_missing");
        // ContentManager rejects null and its IServiceProvider must be assignable in
        // the collectible target closure. Mint MonoGame's own empty service container
        // from the already verified locked assembly; do not pass a probe-local type.
        var serviceProviderType = constructor.GetParameters()[0].ParameterType;
        var serviceContainerType = monoGameAssembly.GetType("Microsoft.Xna.Framework.GameServiceContainer", true)!;
        var serviceProvider = Activator.CreateInstance(serviceContainerType) ?? throw new InvalidOperationException("game_service_container_creation_failed");
        if (!serviceProviderType.IsInstanceOfType(serviceProvider)) throw new InvalidOperationException("game_service_container_provider_type_mismatch");
        var manager = constructor.Invoke(new object?[] { serviceProvider, "Content" });
        var mapType = alc.LoadVerified(xTile).GetType("xTile.Map", true)!;
        var load = managerType.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic).Single(m => m.Name == "Load" && m.IsGenericMethodDefinition && m.GetParameters().Length == 1);
        var map = load.MakeGenericMethod(mapType).Invoke(manager, new object?[] { ExpectedAsset }) ?? throw new InvalidOperationException("map_load_null");
        AssertSnapshot(root, manifest.DeclaredSnapshotClosure, before);
        var records = new List<object>(); var layers = Values(Get(map, "Layers")).ToArray();
        foreach (var layer in layers) { if (layer is null) continue; var layerName = Text(Get(layer,"Id")) ?? Text(Get(layer,"Name")) ?? "<unnamed>"; var width = Number(Get(layer,"LayerWidth")) ?? Number(Get(layer,"Width")) ?? 0; var height = Number(Get(layer,"LayerHeight")) ?? Number(Get(layer,"Height")) ?? 0; if(width < 0 || height < 0 || (long)width*height > 1_000_000) throw new InvalidOperationException("map_dimensions_invalid"); var tiles=Get(layer,"Tiles"); var indexer=tiles?.GetType().GetProperty("Item",new[]{typeof(int),typeof(int)}); for(var y=0;y<height;y++)for(var x=0;x<width;x++){var tile=Invoke(layer,"GetTile",x,y)??Invoke(layer,"GetTile",new PointValue(x,y));if(tile is null&&indexer is not null)try{tile=indexer.GetValue(tiles,new object?[]{x,y});}catch{} if(tile is null)continue;var text=(PropertyValue(Get(tile,"Properties"),"Action")??PropertyValue(Get(tile,"TileIndexProperties"),"Action"))?.ToString();if(text is not null&&System.Text.RegularExpressions.Regex.IsMatch(text,"^Mine(?: [1-9][0-9]*)?$")&&layerName=="Buildings")records.Add(new {layer=layerName,x,y,action=text});}}
        AssertSnapshot(root, manifest.DeclaredSnapshotClosure, before);
        var ordered=records.OrderBy(r=>JsonSerializer.Serialize(r),StringComparer.Ordinal).ToArray(); if(ordered.Length!=ordered.Select(record => JsonSerializer.Serialize(record)).Distinct().Count())throw new InvalidOperationException("duplicate_mine_producer");
        var actual=alc.ActualResolvedLoadSet();
        if (!actual.SequenceEqual(manifest.DeclaredSnapshotClosure.Select(x=>new LoadResolution(x.Identity,"snapshot")).Concat(manifest.AllowedFrameworkFallbackIdentities.Select(x=>new LoadResolution(x,"framework_default"))).Where(x=>alc.WasResolved(x)).OrderBy(x=>x.Identity.DisplayName,StringComparer.Ordinal).ThenBy(x=>x.Source,StringComparer.Ordinal), LoadResolutionComparer.Instance)) throw new InvalidOperationException("actual_resolved_load_set_not_declared");
        Console.WriteLine(JsonSerializer.Serialize(new { state="probed",gameAssemblyVersion=gameAssembly.GetName().Version?.ToString(),mapAsset=ExpectedAsset,mapFile="Content/Maps/Mine.xnb",mapXnbSha256=ExpectedMapDigest,layerCount=layers.Length,layerNames=layers.Select(l=>Text(Get(l,"Id"))??Text(Get(l,"Name"))??"<unnamed>").ToArray(),actionCount=ordered.Length,actions=ordered,note="All Buildings Action text matching exact Mine grammar, sorted; default selection is mechanically derived by the dossier.",loaderProvenance=new { privateSnapshotBoundary=manifest.PrivateSnapshotBoundary, declaredSnapshotClosure=manifest.DeclaredSnapshotClosure, allowedFrameworkFallbackIdentities=manifest.AllowedFrameworkFallbackIdentities, actualResolvedLoadSet=actual } },new JsonSerializerOptions{WriteIndented=true,PropertyNamingPolicy=JsonNamingPolicy.CamelCase})); return 0;
    } finally { alc.Unload(); }
}
catch(Exception error){Console.Error.WriteLine($"probe_failed: {error.GetBaseException().Message}");return 4;}

static bool IsFrameworkAssembly(AssemblyIdentity identity)=>((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")??"").Split(Path.PathSeparator,StringSplitOptions.RemoveEmptyEntries).Select(Path.GetFileNameWithoutExtension).Contains(identity.Name,StringComparer.Ordinal);
static int Discover(string root) { try { if(!IsRegularDirectory(root))throw new InvalidOperationException("invalid_game_root"); var pending=new Queue<string>(new[]{"Stardew Valley.dll"});var seen=new Dictionary<string, SnapshotMember>(StringComparer.Ordinal);var framework=new Dictionary<string, AssemblyIdentity>(StringComparer.Ordinal);while(pending.TryDequeue(out var relative)){if(seen.ContainsKey(relative))continue;var file=VerifiedRegularChild(root,relative)??throw new InvalidOperationException("snapshot_root_assembly_missing:"+relative);var identity=IdentityOf(AssemblyName.GetAssemblyName(file));if(IsFrameworkAssembly(identity))throw new InvalidOperationException("framework_assembly_in_snapshot_closure:"+identity.DisplayName);seen.Add(relative,new SnapshotMember(relative,Digest(file),identity));foreach(var reference in References(file)){if(IsFrameworkAssembly(reference)){if(!TryResolveCompatibleFrameworkReference(reference,out var resolved))throw new InvalidOperationException("incompatible_framework_runtime_fallback:"+reference.DisplayName);framework.TryAdd(resolved.DisplayName,resolved);continue;}var dependency=reference.Name+".dll";if(VerifiedRegularChild(root,dependency) is not null)pending.Enqueue(dependency);}}var closure=seen.Values.OrderBy(x=>x.RelativeFileName,StringComparer.Ordinal).ToArray();var fallbacks=framework.Values.OrderBy(x=>x.DisplayName,StringComparer.Ordinal).ToArray();Console.WriteLine(JsonSerializer.Serialize(new { declaredSnapshotClosure=closure,allowedFrameworkFallbackIdentities=fallbacks },new JsonSerializerOptions{WriteIndented=true,PropertyNamingPolicy=JsonNamingPolicy.CamelCase}));return 0;}catch(Exception e){Console.Error.WriteLine("discovery_failed: "+e.Message);return 3;} }
static bool TryResolveCompatibleFrameworkReference(AssemblyIdentity reference,out AssemblyIdentity resolved) { try { if(!IsFrameworkAssembly(reference))throw new InvalidOperationException();var requested=new AssemblyName(reference.Name) { Version=Version.Parse(reference.Version), CultureName=reference.Culture }; requested.SetPublicKeyToken(reference.PublicKeyToken.Length==0?Array.Empty<byte>():Convert.FromHexString(reference.PublicKeyToken)); resolved=IdentityOf(Assembly.Load(requested).GetName());return IsFrameworkAssembly(resolved)&&resolved.Name==reference.Name&&resolved.Culture==reference.Culture&&resolved.PublicKeyToken==reference.PublicKeyToken&&Version.Parse(resolved.Version)>=Version.Parse(reference.Version); } catch { resolved=default!; return false; } }
static IEnumerable<AssemblyIdentity> References(string file){using var stream=File.OpenRead(file);using var pe=new PEReader(stream);var reader=pe.GetMetadataReader();foreach(var handle in reader.AssemblyReferences){var r=reader.GetAssemblyReference(handle);yield return new AssemblyIdentity(reader.GetString(r.Name),r.Version.ToString(),r.Culture.IsNil?"":reader.GetString(r.Culture),Token(r.PublicKeyOrToken.IsNil?Array.Empty<byte>():reader.GetBlobBytes(r.PublicKeyOrToken)));}}
static void ValidateManifest(LoaderManifest m){if(m.PrivateSnapshotBoundary!="private_temp_acl_current_user_and_SYSTEM_no_reparse_readonly_files")throw new InvalidOperationException("loader_manifest_boundary_invalid");if(m.DeclaredSnapshotClosure.Length==0||!m.DeclaredSnapshotClosure.SequenceEqual(m.DeclaredSnapshotClosure.OrderBy(x=>x.RelativeFileName,StringComparer.Ordinal)))throw new InvalidOperationException("loader_manifest_closure_unordered");if(m.DeclaredSnapshotClosure.Select(x=>x.RelativeFileName).Distinct(StringComparer.Ordinal).Count()!=m.DeclaredSnapshotClosure.Length)throw new InvalidOperationException("loader_manifest_closure_duplicate");foreach(var x in m.DeclaredSnapshotClosure){if(IsFrameworkAssembly(x.Identity)||!SafeRelative(x.RelativeFileName)||!IsHash(x.Sha256)||x.Identity.Name!=Path.GetFileNameWithoutExtension(x.RelativeFileName)||string.IsNullOrEmpty(x.Identity.Version))throw new InvalidOperationException("loader_manifest_member_invalid");}var target=m.DeclaredSnapshotClosure.Where(x=>x.RelativeFileName=="Stardew Valley.dll").ToArray();if(target.Length!=1||target[0].Sha256!=LockedTargetHash)throw new InvalidOperationException("loader_manifest_locked_target_missing_or_drifted");foreach(var required in new[]{"MonoGame.Framework.dll","Stardew Valley.dll","xTile.dll"})if(m.DeclaredSnapshotClosure.Count(x=>x.RelativeFileName==required)!=1)throw new InvalidOperationException("loader_manifest_required_snapshot_resolution_missing:"+required);if(!m.AllowedFrameworkFallbackIdentities.SequenceEqual(m.AllowedFrameworkFallbackIdentities.OrderBy(x=>x.DisplayName,StringComparer.Ordinal))||m.AllowedFrameworkFallbackIdentities.Distinct().Count()!=m.AllowedFrameworkFallbackIdentities.Length||m.AllowedFrameworkFallbackIdentities.Any(x=>!IsFrameworkAssembly(x)))throw new InvalidOperationException("loader_manifest_fallback_invalid");}
static Dictionary<string,string> Snapshot(string root,IEnumerable<SnapshotMember> members)=>members.ToDictionary(x=>x.RelativeFileName,x=>Identity(VerifiedRegularChild(root,x.RelativeFileName)??throw new InvalidOperationException("snapshot_missing")),StringComparer.Ordinal);
static void AssertSnapshot(string root,IEnumerable<SnapshotMember> members,Dictionary<string,string> before){foreach(var x in members){var file=VerifiedRegularChild(root,x.RelativeFileName)??throw new InvalidOperationException("snapshot_missing");if(Digest(file)!=x.Sha256||Identity(file)!=before[x.RelativeFileName])throw new InvalidOperationException("snapshot_identity_or_hash_drift");}}
static string? VerifiedRegularChild(string root,string relative){if(!SafeRelative(relative))return null;var candidate=Path.GetFullPath(Path.Combine(root,relative));var prefix=root.EndsWith(Path.DirectorySeparatorChar)?root:root+Path.DirectorySeparatorChar;return candidate.StartsWith(prefix,StringComparison.OrdinalIgnoreCase)&&IsNonReparseFileTree(candidate)?candidate:null;}
static bool SafeRelative(string x)=>!Path.IsPathRooted(x)&&!x.Contains('\\')&&x.Split('/').All(p=>p.Length>0&&p is not "." and not "..");static bool IsHash(string x)=>x.Length==64&&x.All(c=>(c>='0'&&c<='9')||(c>='a'&&c<='f')||(c>='A'&&c<='F'));static string Token(byte[] x)=>Convert.ToHexString(x).ToLowerInvariant();static string Digest(string x)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(x))).ToLowerInvariant();static string Identity(string x){var i=new FileInfo(x);return $"{i.Length}:{i.LastWriteTimeUtc.Ticks}:{Digest(x)}";}static AssemblyIdentity IdentityOf(AssemblyName n)=>new(n.Name??"",n.Version?.ToString()??"",n.CultureName??"",Token(n.GetPublicKeyToken()??Array.Empty<byte>()));
static bool IsRegularDirectory(string x)=>Directory.Exists(x)&&IsNonReparsePathTree(x);static bool IsNonReparseFileTree(string x)=>File.Exists(x)&&IsNonReparsePathTree(x);static bool IsNonReparsePathTree(string x){try{for(var c=Path.GetFullPath(x);;c=Path.GetDirectoryName(c)??c){if((File.GetAttributes(c)&FileAttributes.ReparsePoint)!=0)return false;var p=Path.GetDirectoryName(c);if(string.IsNullOrEmpty(p)||string.Equals(p,c,StringComparison.OrdinalIgnoreCase))return true;}}catch{return false;}}
static object? Get(object? o,string n)=>o is null?null:o.GetType().GetProperty(n,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)?.GetValue(o)??o.GetType().GetField(n,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)?.GetValue(o);static object? Invoke(object o,string n,params object[] v){foreach(var m in o.GetType().GetMethods(BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).Where(m=>m.Name==n&&m.GetParameters().Length==v.Length))try{return m.Invoke(o,v);}catch{}return null;}static IEnumerable<object?> Values(object? x)=>x is IEnumerable e&&x is not string?e.Cast<object?>():Array.Empty<object?>();static object? PropertyValue(object? p,string k){if(p is IDictionary d)foreach(DictionaryEntry e in d)if(e.Key?.ToString()==k)return e.Value;try{return p?.GetType().GetProperty("Item",new[]{typeof(string)})?.GetValue(p,new object?[]{k});}catch{return null;}}static int? Number(object? x)=>x is int i?i:int.TryParse(x?.ToString(),out var n)?n:null;static string? Text(object? x)=>x?.ToString();
sealed record PointValue(int X,int Y); sealed record AssemblyIdentity(string Name,string Version,string Culture,string PublicKeyToken){public string DisplayName=>$"{Name}, Version={Version}, Culture={(Culture==""?"neutral":Culture)}, PublicKeyToken={(PublicKeyToken==""?"null":PublicKeyToken)}";}sealed record SnapshotMember(string RelativeFileName,string Sha256,AssemblyIdentity Identity);sealed record LoaderManifest(string PrivateSnapshotBoundary,SnapshotMember[] DeclaredSnapshotClosure,AssemblyIdentity[] AllowedFrameworkFallbackIdentities);sealed record LoadResolution(AssemblyIdentity Identity,string Source);sealed class LoadResolutionComparer:IEqualityComparer<LoadResolution>{public static readonly LoadResolutionComparer Instance=new();public bool Equals(LoadResolution? x,LoadResolution? y)=>x?.Identity==y?.Identity&&x?.Source==y?.Source;public int GetHashCode(LoadResolution x)=>HashCode.Combine(x.Identity,x.Source);}
sealed class FrameworkPolicy { public static bool IsFrameworkAssembly(AssemblyIdentity identity)=>((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")??"").Split(Path.PathSeparator,StringSplitOptions.RemoveEmptyEntries).Select(Path.GetFileNameWithoutExtension).Contains(identity.Name,StringComparer.Ordinal); public static bool TryResolveCompatibleFrameworkReference(AssemblyIdentity reference,out AssemblyIdentity resolved) { try { if(!IsFrameworkAssembly(reference))throw new InvalidOperationException();var requested=new AssemblyName(reference.Name) { Version=Version.Parse(reference.Version), CultureName=reference.Culture }; requested.SetPublicKeyToken(reference.PublicKeyToken.Length==0?Array.Empty<byte>():Convert.FromHexString(reference.PublicKeyToken)); resolved=IdentityOf(Assembly.Load(requested).GetName());return IsFrameworkAssembly(resolved)&&resolved.Name==reference.Name&&resolved.Culture==reference.Culture&&resolved.PublicKeyToken==reference.PublicKeyToken&&Version.Parse(resolved.Version)>=Version.Parse(reference.Version); } catch { resolved=default!; return false; } } private static AssemblyIdentity IdentityOf(AssemblyName n)=>new(n.Name??"",n.Version?.ToString()??"",n.CultureName??"",Convert.ToHexString(n.GetPublicKeyToken()??Array.Empty<byte>()).ToLowerInvariant()); }
sealed class LockedGameLoadContext:AssemblyLoadContext { private readonly string root; private readonly LoaderManifest manifest; private readonly List<LoadResolution> actual=new(); public LockedGameLoadContext(string root,LoaderManifest manifest):base("position-for-mine-entry-content-probe",true){this.root=root;this.manifest=manifest;} private static string? FileAt(string root,string relative){var file=Path.GetFullPath(Path.Combine(root,relative));return File.Exists(file)?file:null;} private static string HashAt(string file)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(file))).ToLowerInvariant(); private static AssemblyIdentity NameAt(AssemblyName name)=>new(name.Name??"",name.Version?.ToString()??"",name.CultureName??"",Convert.ToHexString(name.GetPublicKeyToken()??Array.Empty<byte>()).ToLowerInvariant()); public Assembly LoadVerified(SnapshotMember member){if(FrameworkPolicy.IsFrameworkAssembly(member.Identity))throw new InvalidOperationException("framework_snapshot_load_forbidden:"+member.Identity.DisplayName);var file=FileAt(root,member.RelativeFileName)??throw new InvalidOperationException("snapshot_member_missing");if(HashAt(file)!=member.Sha256||NameAt(AssemblyName.GetAssemblyName(file))!=member.Identity)throw new InvalidOperationException("snapshot_member_identity_or_hash_drift");var assembly=LoadFromAssemblyPath(file);Record(member.Identity,"snapshot");return assembly;} protected override Assembly? Load(AssemblyName requested){var identity=NameAt(requested);if(FrameworkPolicy.IsFrameworkAssembly(identity)){if(!FrameworkPolicy.TryResolveCompatibleFrameworkReference(identity,out var resolved)||!manifest.AllowedFrameworkFallbackIdentities.Contains(resolved))throw new FileLoadException("undeclared_or_incompatible_framework_runtime_fallback:"+identity.DisplayName);Record(resolved,"framework_default");return null;}var member=manifest.DeclaredSnapshotClosure.SingleOrDefault(x=>x.Identity==identity);if(member is not null)return LoadVerified(member);throw new FileLoadException("undeclared_or_identity_mismatched_assembly_request:"+identity.DisplayName);} private void Record(AssemblyIdentity identity,string source){if(!actual.Contains(new LoadResolution(identity,source),LoadResolutionComparer.Instance))actual.Add(new(identity,source));} public bool WasResolved(LoadResolution resolution)=>actual.Contains(resolution,LoadResolutionComparer.Instance); public LoadResolution[] ActualResolvedLoadSet()=>actual.OrderBy(x=>x.Identity.DisplayName,StringComparer.Ordinal).ThenBy(x=>x.Source,StringComparer.Ordinal).ToArray(); }
